CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'base',
  name TEXT,
  api_token TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS service_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 25001),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT NOT NULL,
  customer_phone_normalized TEXT,
  device_type TEXT NOT NULL,
  device_model TEXT,
  issue_description TEXT NOT NULL,
  additional_notes TEXT,
  disclaimer_language TEXT DEFAULT 'sv',
  status TEXT DEFAULT 'Nytt',
  user_id TEXT,
  cost_proposal_approved BOOLEAN NOT NULL DEFAULT FALSE,
  internal_notes TEXT,
  work_done_summary TEXT,
  final_cost TEXT,
  diagnosis TEXT,
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  customer_notified_at TIMESTAMPTZ,
  picked_up_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS service_tickets_ticket_number_idx ON service_tickets (ticket_number);
CREATE INDEX IF NOT EXISTS service_tickets_phone_norm_idx ON service_tickets (customer_phone_normalized);

CREATE TABLE IF NOT EXISTS message_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID REFERENCES service_tickets(id) ON DELETE SET NULL,
  channel TEXT NOT NULL,
  direction TEXT NOT NULL,
  to_number TEXT,
  from_number TEXT,
  subject TEXT,
  body TEXT,
  provider TEXT,
  provider_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
