CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS service_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 25001),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT NOT NULL,
  device_type TEXT NOT NULL,
  device_model TEXT,
  issue_description TEXT NOT NULL,
  additional_notes TEXT,
  disclaimer_language TEXT DEFAULT 'sv',
  status TEXT DEFAULT 'Nytt',
  user_id TEXT,
  cost_proposal_approved BOOLEAN NOT NULL DEFAULT FALSE,
  internal_notes TEXT,
  work_done_summary TEXT,
  final_cost TEXT,
  diagnosis TEXT,
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS service_tickets_ticket_number_idx ON service_tickets (ticket_number);
